import Layout from 'components/Layout/Layout';
import React from 'react';
import { Card, Grid } from './styles';

const Home: React.FC = () => {
  return (
    <Layout>
      <Grid>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
        <Card>
          <a href="test">
            <img
              src="https://i.pravatar.cc/200?u=5f1d7f3e5dc58af42fc39242"
              alt="teste"
            />
            <div>
              <strong>name:fulano</strong>
              <p>age:22</p>
              <p>eyeColor:bar</p>
              <p>company:foo</p>
              <p>email:a@a.com</p>
            </div>
          </a>
        </Card>
      </Grid>
    </Layout>
  );
};

export default Home;
